name: cloudrun-deploy
on:
  push:
    branches:
      - main
      - feat/actions

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}

    - name: Build Docker Image
      shell: bash
      run: docker build -t europe-west1-docker.pkg.dev/padok-training-lab/chap-semantle/le-semantle-server:$GITHUB_SHA -t europe-west1-docker.pkg.dev/padok-training-lab/chap-semantle/le-semantle-server:latest .

    - name: Setup GCP SDK and Docker Client
      uses: latrock/gcp-artifact-registry-auth@v0.1.1
      with:
        gcp-sa-creds-json: ${{ secrets.CREDENTIALS_JSON }}
        registry: europe-west1-docker.pkg.dev

    - name: Push Docker Image to Artifact Registry
      shell: bash
      run: |-
        docker push europe-west1-docker.pkg.dev/padok-training-lab/chap-semantle/le-semantle-server:latest
        docker push europe-west1-docker.pkg.dev/padok-training-lab/chap-semantle/le-semantle-server:$GITHUB_SHA

    - id: 'deploy'
      name: 'Deploy on Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'le-semantle-server'
        image: 'europe-west1-docker.pkg.dev/padok-training-lab/chap-semantle/le-semantle-server:CI_COMMIT_SHA'
        region: europe-north1

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
