name: cloudrun-deploy
on:
  push:
    branches:
      - main
      - feat/actions

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}

    - id: 'deploy'
      name: 'Deploy on Cloud Run'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'le-semantle-server'
        image: 'europe-west1-docker.pkg.dev/padok-training-lab/chap-semantle/le-semantle-server'
        region: europe-north1

    - name: 'Use output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
